[package]
name = "basic-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
dotenvy = "0.15"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.9", features = [
    "runtime-tokio",
        "tls-native-tls",
        "postgres",
        "migrate",
        "sqlx-toml",
        "json",
        "chrono",
        "uuid",
] }

[dependencies.uuid]
version = "1.26.1"
features = [
    "v4",
    "serde"
]
